create extension if not exists pgcrypto;

create type public.app_role as enum ('coach', 'admin');
create type public.poll_status as enum ('draft', 'open', 'closed', 'published');
create type public.ballot_status as enum ('draft', 'submitted', 'reopened');
create type public.fencing_gender as enum ('Men', 'Women');
create type public.fencing_weapon as enum ('Team', 'Epee', 'Foil', 'Sabre');
create type public.poll_scope as enum ('Overall', 'DIII');

create table public.seasons (
    id uuid primary key default gen_random_uuid(),
    slug text unique not null,
    name text not null,
    starts_on date not null,
    ends_on date not null,
    is_active boolean not null default false
);

create table public.schools (
    id bigint primary key,
    name text not null,
    short_name text,
    logo_url text,
    conference text not null default 'Unassigned',
    region text not null default 'Unassigned',
    created_at timestamptz not null default now()
);

create table public.programs (
    id uuid primary key default gen_random_uuid(),
    school_id bigint not null references public.schools(id) on delete cascade,
    legacy_team_id bigint unique not null,
    gender public.fencing_gender not null,
    unique (school_id, gender)
);

create table public.program_seasons (
    id uuid primary key default gen_random_uuid(),
    season_id uuid not null references public.seasons(id) on delete cascade,
    program_id uuid not null references public.programs(id) on delete cascade,
    division smallint not null check (division in (1, 2, 3)),
    conference text not null default 'Unassigned',
    region text not null default 'Unassigned',
    unique (season_id, program_id)
);

create table public.matches (
    id bigint generated by default as identity primary key,
    source_id bigint,
    season_id uuid not null references public.seasons(id) on delete cascade,
    fenced_on date not null,
    gender public.fencing_gender not null,
    left_program_id uuid not null references public.programs(id),
    right_program_id uuid not null references public.programs(id),
    left_sabre smallint not null check (left_sabre >= 0),
    left_foil smallint not null check (left_foil >= 0),
    left_epee smallint not null check (left_epee >= 0),
    right_sabre smallint not null check (right_sabre >= 0),
    right_foil smallint not null check (right_foil >= 0),
    right_epee smallint not null check (right_epee >= 0),
    host text not null,
    submitted_by uuid references auth.users(id),
    created_at timestamptz not null default now(),
    unique (season_id, source_id)
);

create table public.spi_results (
    id uuid primary key default gen_random_uuid(),
    season_id uuid not null references public.seasons(id) on delete cascade,
    program_id uuid not null references public.programs(id) on delete cascade,
    weapon public.fencing_weapon not null,
    spi numeric not null,
    power_rating numeric,
    calculated_at timestamptz not null default now(),
    unique (season_id, program_id, weapon)
);

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    role public.app_role not null default 'coach',
    school_id bigint references public.schools(id),
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table public.poll_periods (
    id uuid primary key default gen_random_uuid(),
    season_id uuid not null references public.seasons(id) on delete cascade,
    month smallint not null check (month in (10, 11, 12, 1)),
    label text not null,
    status public.poll_status not null default 'draft',
    opens_at timestamptz,
    closes_at timestamptz,
    unique (season_id, month)
);

create table public.ballot_definitions (
    id uuid primary key default gen_random_uuid(),
    period_id uuid not null references public.poll_periods(id) on delete cascade,
    gender public.fencing_gender not null,
    weapon public.fencing_weapon not null,
    scope public.poll_scope not null,
    rank_limit smallint not null check (rank_limit > 0),
    unique (period_id, gender, weapon, scope)
);

create table public.ballots (
    id uuid primary key default gen_random_uuid(),
    definition_id uuid not null references public.ballot_definitions(id) on delete cascade,
    voter_id uuid not null references public.profiles(id) on delete cascade,
    status public.ballot_status not null default 'draft',
    submitted_at timestamptz,
    updated_at timestamptz not null default now(),
    unique (definition_id, voter_id)
);

create table public.ballot_rankings (
    ballot_id uuid not null references public.ballots(id) on delete cascade,
    program_id uuid not null references public.programs(id) on delete cascade,
    rank smallint not null check (rank > 0),
    primary key (ballot_id, program_id),
    unique (ballot_id, rank)
);

create table public.published_poll_results (
    definition_id uuid not null references public.ballot_definitions(id) on delete cascade,
    program_id uuid not null references public.programs(id) on delete cascade,
    points integer not null,
    rank integer not null,
    first_place_votes integer not null default 0,
    published_at timestamptz not null default now(),
    primary key (definition_id, program_id)
);

create table public.ballot_audit_log (
    id bigint generated always as identity primary key,
    ballot_id uuid not null references public.ballots(id) on delete cascade,
    actor_id uuid not null references auth.users(id),
    action text not null,
    detail jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create or replace function public.validate_ballot_ranking()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    definition public.ballot_definitions%rowtype;
    program_gender public.fencing_gender;
    program_division smallint;
begin
    select bd.* into definition
    from public.ballots b join public.ballot_definitions bd on bd.id = b.definition_id
    where b.id = new.ballot_id;
    select p.gender, ps.division into program_gender, program_division
    from public.programs p
    join public.program_seasons ps on ps.program_id = p.id
    join public.poll_periods pp on pp.season_id = ps.season_id and pp.id = definition.period_id
    where p.id = new.program_id;
    if new.rank > definition.rank_limit then raise exception 'Rank exceeds ballot limit'; end if;
    if program_gender <> definition.gender then raise exception 'Program gender does not match ballot'; end if;
    if definition.scope = 'DIII' and program_division <> 3 then raise exception 'Only Division III programs are eligible'; end if;
    return new;
end;
$$;

create trigger validate_ballot_ranking_before_write
before insert or update on public.ballot_rankings
for each row execute function public.validate_ballot_ranking();

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
    select role from public.profiles where id = auth.uid() and active = true
$$;

create or replace function public.poll_is_closed(definition uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select pp.status in ('closed', 'published')
    from public.ballot_definitions bd
    join public.poll_periods pp on pp.id = bd.period_id
    where bd.id = definition
$$;

create or replace function public.poll_is_open(definition uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select pp.status = 'open'
    from public.ballot_definitions bd
    join public.poll_periods pp on pp.id = bd.period_id
    where bd.id = definition
$$;

create or replace function public.submit_ballot(target_ballot uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    expected_count integer;
    actual_count integer;
    owner_id uuid;
    period_status public.poll_status;
begin
    select b.voter_id, bd.rank_limit, pp.status
    into owner_id, expected_count, period_status
    from public.ballots b
    join public.ballot_definitions bd on bd.id = b.definition_id
    join public.poll_periods pp on pp.id = bd.period_id
    where b.id = target_ballot;

    if owner_id is null or (owner_id <> auth.uid() and public.current_app_role() <> 'admin') then
        raise exception 'Ballot not found or access denied';
    end if;
    if period_status <> 'open' then
        raise exception 'This poll is not open';
    end if;

    select count(*) into actual_count
    from public.ballot_rankings where ballot_id = target_ballot;
    if actual_count <> expected_count then
        raise exception 'Ballot requires exactly % ranked programs', expected_count;
    end if;

    update public.ballots
    set status = 'submitted', submitted_at = now(), updated_at = now()
    where id = target_ballot;
    insert into public.ballot_audit_log (ballot_id, actor_id, action)
    values (target_ballot, auth.uid(), 'submitted');
end;
$$;

create or replace function public.publish_poll_period(target_period uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if public.current_app_role() <> 'admin' then
        raise exception 'Admin access required';
    end if;

    delete from public.published_poll_results p
    using public.ballot_definitions d
    where p.definition_id = d.id and d.period_id = target_period;

    insert into public.published_poll_results
        (definition_id, program_id, points, rank, first_place_votes)
    select definition_id,
           program_id,
           points,
           rank() over (partition by definition_id order by points desc)::integer,
           first_place_votes
    from (
        select b.definition_id,
               r.program_id,
               sum(d.rank_limit - r.rank + 1)::integer as points,
               count(*) filter (where r.rank = 1)::integer as first_place_votes
        from public.ballots b
        join public.ballot_rankings r on r.ballot_id = b.id
        join public.ballot_definitions d on d.id = b.definition_id
        where d.period_id = target_period and b.status = 'submitted'
        group by b.definition_id, r.program_id
    ) totals;

    update public.poll_periods set status = 'published' where id = target_period;
end;
$$;

create or replace function public.initialize_poll_period(target_period uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    selected_season uuid;
    selected_gender public.fencing_gender;
    selected_weapon public.fencing_weapon;
    d3_count integer;
begin
    if public.current_app_role() <> 'admin' then
        raise exception 'Admin access required';
    end if;
    select season_id into selected_season from public.poll_periods where id = target_period;
    foreach selected_gender in array enum_range(null::public.fencing_gender) loop
        select count(*) into d3_count
        from public.program_seasons ps
        join public.programs p on p.id = ps.program_id
        where ps.season_id = selected_season and ps.division = 3 and p.gender = selected_gender;
        foreach selected_weapon in array enum_range(null::public.fencing_weapon) loop
            insert into public.ballot_definitions (period_id, gender, weapon, scope, rank_limit)
            values
                (target_period, selected_gender, selected_weapon, 'Overall', 15),
                (target_period, selected_gender, selected_weapon, 'DIII', greatest(d3_count, 1))
            on conflict (period_id, gender, weapon, scope) do update
            set rank_limit = excluded.rank_limit;
        end loop;
    end loop;
end;
$$;

alter table public.seasons enable row level security;
alter table public.schools enable row level security;
alter table public.programs enable row level security;
alter table public.program_seasons enable row level security;
alter table public.matches enable row level security;
alter table public.spi_results enable row level security;
alter table public.profiles enable row level security;
alter table public.poll_periods enable row level security;
alter table public.ballot_definitions enable row level security;
alter table public.ballots enable row level security;
alter table public.ballot_rankings enable row level security;
alter table public.published_poll_results enable row level security;
alter table public.ballot_audit_log enable row level security;

create policy "Public reference data" on public.seasons for select using (true);
create policy "Public schools" on public.schools for select using (true);
create policy "Public programs" on public.programs for select using (true);
create policy "Public program seasons" on public.program_seasons for select using (true);
create policy "Public matches" on public.matches for select using (true);
create policy "Public SPI" on public.spi_results for select using (true);
create policy "Public published polls" on public.published_poll_results for select using (true);
create policy "Authenticated poll periods" on public.poll_periods for select using (auth.uid() is not null or status = 'published');
create policy "Visible ballot definitions" on public.ballot_definitions for select using (
    auth.uid() is not null or exists (
        select 1 from public.poll_periods pp where pp.id = period_id and pp.status = 'published'
    )
);
create policy "Profile visibility" on public.profiles for select using (auth.uid() = id or public.current_app_role() = 'admin' or auth.uid() is not null);

create policy "Coaches see own or closed ballots" on public.ballots for select
using (voter_id = auth.uid() or public.current_app_role() = 'admin' or public.poll_is_closed(definition_id));
create policy "Coaches create own ballots" on public.ballots for insert
with check ((voter_id = auth.uid() and public.poll_is_open(definition_id)) or public.current_app_role() = 'admin');
create policy "Coaches update own ballots" on public.ballots for update
using ((voter_id = auth.uid() and public.poll_is_open(definition_id)) or public.current_app_role() = 'admin')
with check ((voter_id = auth.uid() and public.poll_is_open(definition_id)) or public.current_app_role() = 'admin');

create policy "Rankings follow ballot visibility" on public.ballot_rankings for select
using (exists (
    select 1 from public.ballots b
    where b.id = ballot_id
      and (b.voter_id = auth.uid() or public.current_app_role() = 'admin' or public.poll_is_closed(b.definition_id))
));
create policy "Coaches edit own rankings" on public.ballot_rankings for all
using (exists (select 1 from public.ballots b where b.id = ballot_id and ((b.voter_id = auth.uid() and public.poll_is_open(b.definition_id)) or public.current_app_role() = 'admin')))
with check (exists (select 1 from public.ballots b where b.id = ballot_id and ((b.voter_id = auth.uid() and public.poll_is_open(b.definition_id)) or public.current_app_role() = 'admin')));

create policy "Admins manage seasons" on public.seasons for all using (public.current_app_role() = 'admin');
create policy "Admins manage schools" on public.schools for all using (public.current_app_role() = 'admin');
create policy "Admins manage programs" on public.programs for all using (public.current_app_role() = 'admin');
create policy "Admins manage program seasons" on public.program_seasons for all using (public.current_app_role() = 'admin');
create policy "Admins manage matches" on public.matches for all using (public.current_app_role() = 'admin');
create policy "Admins manage SPI" on public.spi_results for all using (public.current_app_role() = 'admin');
create policy "Admins manage profiles" on public.profiles for all using (public.current_app_role() = 'admin');
create policy "Admins manage poll periods" on public.poll_periods for all using (public.current_app_role() = 'admin');
create policy "Admins manage definitions" on public.ballot_definitions for all using (public.current_app_role() = 'admin');
create policy "Admins read audit" on public.ballot_audit_log for select using (public.current_app_role() = 'admin');

grant execute on function public.submit_ballot(uuid) to authenticated;
grant execute on function public.publish_poll_period(uuid) to authenticated;
grant execute on function public.initialize_poll_period(uuid) to authenticated;
